spring:
  # Database connection setting.
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://220.76.63.77:3306/map?autoReconnect=true
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 4
  # Spring static resource hot reload.
  devtools:
    livereload:
      enabled: true

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#spring:
#  h2:
#    console:
#      enabled: true
#  profiles:
#    active: local
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
#      driver-class-name: org.h2.Driver
#      username: root
#      password: mysql

# MyBatis
mybatis:
  # mapper.xml 위치 지정.
  mapper-locations: mybatis-mapper/**/*.xml

  # model 프로퍼티 camel case 설정.
  configuration:
    map-underscore-to-camel-case: true

    # MyBatis update시 null 처리. (cache-enabeld = false , jdbc-type-for-null = null) => null 값을 넣는 것을 허용.
    # cache-enabled: false
    # jdbc-type-for-null: null

  # 패키지 명을 생략할 수 있도록 alias 설정.
  type-aliases-package: com.zetta.memo.page.memo

# log level config.
#logging:
#  level:
#    jdbc.sqlonly: DEBUG
#    org.springframework.web: ERROR
#    com.zaxxer.hikari.HikariDataSource: ERROR

# log4jdbc.log4j2.properties에 설정해야 하는 값인데 YML 에 설정해도 안된다.
#log4jdbc:
#  spylogdelegator:
#    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
#  dump:
#    sql:
#      maxlinelength: 0
#  auto:
#    load:
#      popular:
#        drivers: false
#  drivers: com.mysql.cj.jdbc.Driver
